// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TeamAscend.Agapay.Web.Models;

public partial class AppGlobalSetting
{
    public int ID { get; set; }

    public string SettingsName { get; set; }

    public string SettingsValue { get; set; }

    public bool IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}