// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TeamAscend.Agapay.Web.Models;

public partial class Phonebook
{
    public int ID { get; set; }

    public string ContactName { get; set; }

    public string ContactNumber { get; set; }

    public string Location { get; set; }

    public string Agency { get; set; }

    public string District { get; set; }

    public string Barangay { get; set; }

    public string BarangayCaptain { get; set; }

    public string EmergencyHotline { get; set; }

    public bool IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}